import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-utility-pole-attachment-rent-recovery",
  "engine": "recovery",
  "title": "Utility Pole Attachment Rent Recovery",
  "shortTitle": "Utility Pole Attachment Rent Recovery",
  "tagline": "Recover missing pole rent, unauthorized attachment fees, make-ready costs, and late payments from attachers.",
  "industry": "Utility Asset Revenue Assurance",
  "buyer": "Electric utilities and pole owners",
  "uiPort": 4719,
  "apiPort": 5719,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Utility Pole Attachment Rent Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments in one accountable workflow. Recover missing pole rent, unauthorized attachment fees, make-ready costs, and late payments from attachers.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Utility Pole Attachment Rent Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("pole-inventory-registry","UPA01","Pole inventory registry","Execute pole inventory registry using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed pole inventory registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Pole inventory registry Reference","text","UPA01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("attacher-agreement-library","UPA02","Attacher agreement library","Execute attacher agreement library using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed attacher agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Attacher agreement library Reference","text","UPA02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("attachment-survey-ingestion","UPA03","Attachment survey ingestion","Execute attachment survey ingestion using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed attachment survey ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Attachment survey ingestion Reference","text","UPA03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("authorized-attachment-matching","UPA04","Authorized attachment matching","Execute authorized attachment matching using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed authorized attachment matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Authorized attachment matching Reference","text","UPA04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("unauthorized-attachment-detection","UPA05","Unauthorized attachment detection","Execute unauthorized attachment detection using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed unauthorized attachment detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Unauthorized attachment detection Reference","text","UPA05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("rate-formula-calculation","UPA06","Rate formula calculation","Execute rate formula calculation using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed rate formula calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Rate formula calculation Reference","text","UPA06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("space-factor-validation","UPA07","Space factor validation","Execute space factor validation using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed space factor validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Space factor validation Reference","text","UPA07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("carrying-charge-calculation","UPA08","Carrying charge calculation","Execute carrying charge calculation using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed carrying charge calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Carrying charge calculation Reference","text","UPA08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("joint-use-offset","UPA09","Joint-use offset","Execute joint-use offset using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed joint-use offset decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Joint-use offset Reference","text","UPA09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("make-ready-cost-recovery","UPA10","Make-ready cost recovery","Execute make-ready cost recovery using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed make-ready cost recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Make-ready cost recovery Reference","text","UPA10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("back-rent-calculation","UPA11","Back-rent calculation","Execute back-rent calculation using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed back-rent calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Back-rent calculation Reference","text","UPA11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("attacher-invoice-generation","UPA12","Attacher invoice generation","Execute attacher invoice generation using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed attacher invoice generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Attacher invoice generation Reference","text","UPA12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("dispute-workflow","UPA13","Dispute workflow","Execute dispute workflow using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Dispute workflow Reference","text","UPA13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("cash-reconciliation","UPA14","Cash reconciliation","Execute cash reconciliation using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Cash reconciliation Reference","text","UPA14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]}),
feature("territory-attacher-analytics","UPA15","Territory attacher analytics","Execute territory attacher analytics using pole inventories, attachment licenses, make-ready work, surveys, occupancy, attachment counts, rates, unauthorized attachments, invoices, and payments.","Produce a governed territory attacher analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Attacher / Pole Population","text","Attacher / Pole Population · Standard Case"],["caseReference","Territory attacher analytics Reference","text","UPA15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1552500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1878525],["domainDriver","Attachment Type","select","Communications",["Communications","Wireless","Joint use"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Pole inventory registry case","Attacher agreement library case","Attachment survey ingestion case","Authorized attachment matching case","Unauthorized attachment detection case"]})
]);
